src/post/urls.py
from django.conf.urls import url
from . import views

app_name = 'post'

urlpatterns = [
#post/pk/name
    url(r'^(?P<slug>\S+)/$',views.PostView.as_view(),name='display'),
]

src/src/urls.py
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
#import de views
from .views import *
#from contacto import views

urlpatterns = [
    #urldefault de la pagina
    url(r'^$',IndexView.as_view(), name='inicio'),
    #subapps
    url(r'^post/',include('post.urls')),
    url(r'^about/$', about, name='about'),
    url(r'^contact/$', contact, name='contact'),
    #admin views
    url(r'^admin/', admin.site.urls),
    #apps de terceros
    url(r'^accounts/', include('registration.backends.default.urls')),
    url('^markdown/', include( 'django_markdown.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/post/models.py
from django_markdown.models import MarkdownField
from django.db import models
# Create your models here.

class Tag(models.Model):
    slug = models.SlugField(max_length=200,unique=True)

    def __str__(self):
        return self.slug


class PostQuerySet(models.QuerySet):
    def published(self):
        return self.filter(publish=True)

class Post(models.Model):
    title = models.CharField(max_length=100,blank=True,null=True)
    subtitle = models.CharField(max_length=100)
    content = MarkdownField()
    image = models.FileField()
    slug = models.SlugField(max_length=200, unique=True)
    publish = models.BooleanField(default=True)
    created = models.DateField(auto_now_add=True, auto_now=False)
    tags = models.ManyToManyField(Tag)


    objects = PostQuerySet().as_manager()

    def __str__(self):
        return self.title + ' . '

    def get_absolute_url(self):
        return reverse("display", kwargs={"slug": self.slug})

    class Meta:
        verbose_name = "Blog Entry"
        verbose_name_plural = "Blog Entries"
        ordering = ["-created"]

src/src/forms.py
from django import forms

class ContactForm(forms.Form):
	nombre = forms.CharField(required=False)
	email = forms.EmailField()
	mensaje = forms.CharField(widget=forms.Textarea)

src/post/views.py
from django.views import generic
from django.shortcuts import render
from django.views.generic import View
from .models import Post
# Create your views here.

class PostView(generic.DetailView):
    model = Post
    template_name = 'post.html'

src/src/views.py
from django.shortcuts import render
#generics views
from django.views.generic import View
from django.views import generic
#settings and senmail
from django.conf import settings
from django.core.mail import send_mail
# views and forms
from .forms import  ContactForm
from post import models

# Create your views here.

class IndexView(generic.ListView):
    template_name = 'index.html'
    paginate_by = 5

    def get_queryset(self):
        return models.Post.objects.published()
#def inicio(request):
#	model = models
#	return render(request, "index.html", {})


def contact(request):
	titulo = "Contacto"
	form = ContactForm(request.POST or None)
	if form.is_valid():
#Forma de mostrar decente
#		for key in form.cleaned_data:
#			print(key)
#			print(form.cleaned_data.get(key))
#forma de mostrar a mano
		form_email = form.cleaned_data.get("email")
		form_mensaje = form.cleaned_data.get("mensaje")
		form_nombre = form.cleaned_data.get("nombre")
		asunto = 'Form de contacto'
		email_from = settings.EMAIL_HOST_USER
		email_to = [settings.EMAIL]
		email_mensaje = "%s: %s enviado por : %s" %(form_nombre,form_mensaje,form_email)
		send_mail(asunto,
			email_mensaje,
			email_from,
			email_to,
			fail_silently=False
			)
#		print (email,mensaje,nombre)
	context ={
		"form":form,
		"titulo":titulo,
	}
	return render(request, "contact.html", context)

def about(request):
	return render(request,'about.html',{})

src/templates/about.html
{% extends "base.html" %}
{% load static %}
{% block title %}
About
{% endblock %}
{% block image %}
<header class="intro-header" style="background-image: url({% static 'img/about-bg.jpg' %})">
{% endblock %}
{% block header %}
About
{% endblock %}
{% block subhead %}
This is what I do.
{% endblock %}
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below.
    <header class="intro-header" style="background-image: url('img/about-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>About Me</h1>
                        <hr class="small">
                        <span class="subheading">This is what I do.</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum molestiae debitis nobis, quod sapiente qui voluptatum, placeat magni repudiandae accusantium fugit quas labore non rerum possimus, corrupti enim modi! Et.</p>
        </div>
    </div>
</div>
{% endblock %}

src/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>
    {% include "head_css.html" %}
</head>

<body>
  {% include "navbar.html" %}
  <!-- Page Header -->
  <!-- Set your background image for this header on the line below. -->
  {% block image %}
  <header class="intro-header" style="background-image: url({% static 'img/home-bg.jpg' %})">
  {% endblock %}
      <div class="container">
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1" aling = 'justify'>
                  <div class="site-heading">
                      <h1>{% block header %}{% endblock %}</h1>
                      <hr class="small">
                      <span class="subheading">{% block subhead %}{% endblock %}</span>
                      {% block datep %}

                      {% endblock %}
                  </div>
              </div>
          </div>
      </div>
  </header>
    {% block content %}

    {% endblock %}
    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <ul class="list-inline text-center">
                        <li>
                            <a href="https://twitter.com/senjuana">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://www.linkedin.com/in/josé-ernesto-ruiz-valdivia-035832124/">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-linkedin fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="https://gitlab.com/senjuana">
                                <span class="fa-stack fa-lg">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-gitlab fa-stack-1x fa-inverse"></i>
                                </span>
                            </a>
                        </li>
                    </ul>
                    <p class="copyright text-muted">Copyright &copy; Senjuana Blog 2017</p>
                </div>
            </div>
        </div>
    </footer>
    {% include "js_core.html" %}

</body>

</html>

src/templates/contact.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  {{ titulo }}
{% endblock %}
{% block image %}
<header class="intro-header" style="background-image: url({% static 'img/contact-bg.jpg' %})">
{% endblock %}
{% block header %}
  Contact me
{% endblock %}
{% block subhead %}
  You can contact me
{% endblock %}

{% block content %}
  {% include "forms.html" %}
{% endblock %}

src/templates/forms.html
{% load crispy_forms_tags %}
<hr/>
<div class="row">
  <div class="col-sm-6 col-sm-offset-3">
    {% if titulo %}
      <h1 class="text-aling-center">{{ titulo }}</h1>
    {% endif %}
    <form method="post" action="">
      {% csrf_token %}
      {{ form|crispy }}
      <input class="btn btn-primary" type="submit"  value="Enviar"/>
    </form>
  </div>
</div>

src/templates/head_css.html
{% load static %}

<!-- Bootstrap Core CSS -->
<link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Theme CSS -->
<link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">

<!-- Custom Fonts -->
<link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
<![endif]-->

src/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Senjuana's Blog
{% endblock %}
{% block header %}
Blog
{% endblock %}
{% block subhead %}
Linux is cool until you compile it.
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
      {% for post in object_list  %}
        <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            <div class="post-preview">
                <a href="{% url 'post:display' slug=post.slug %}">
                    <h2 class="post-title">
                        {{post.title}}
                    </h2>
                    <h3 class="post-subtitle">
                        {{post.subtitle}}
                    </h3>
                </a>
                <p class="post-meta">Posted by <a href="#">Senjuana</a> on {{post.created}}</p>
            </div>
            <hr>
          </div>
      {% endfor %}

      </div>

      {% if is_paginated %}
            <ul class="pager">
              <li {% if not page_obj.has_previous %}class="disabled"{% endif %}><a {% if page_obj.has_previous %}href="?page={{ page_obj.previous_page_number }}"{% endif %}>Prev</a></li>
              <li {% if not page_obj.has_next %}class="disabled"{% endif %}><a {% if page_obj.has_next %}href="?page={{ page_obj.next_page_number }}"{% endif %}>Next</a></li>
            </ul>
    {% endif %}
    </div>
</div>
{% endblock %}

src/templates/js_core.html
{% load static %}
<!-- jQuery -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>


<!-- Contact Form JavaScript
<script src="js/jqBootstrapValidation.js"></script>
<script src="js/contact_me.js"></script>

<!-- Theme JavaScript -->
<script src="{% static 'js/clean-blog.min.js' %}"></script>

src/templates/navbar.html
{% load static %}
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="/">Senjuana</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="/">Home</a>
                </li>
                <li>
                    <a href="{% url 'about' %}">About</a>
                </li>
                <!--<li>
                    <a href="#">Sample Post</a>
                </li>-->
                <li>
                    <a href="{% url 'contact' %}">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

src/templates/post.html
{% extends "base.html" %}
{% load static %}
{% load django_markdown %}

{% block title %}
Post
{% endblock %}

{% block header %}
  {{post.title}}
{% endblock %}

{% block subhead %}
  {{post.subtitle}}
{% endblock %}

{% block image %}
  <header class="intro-header" style="background-image: url({{post.image.url}})">
{% endblock %}

{% block datep %}
  <br>
  <span class="meta">Posted by <a href="#">Senjuana</a> on {{post.created}}</span>
{% endblock %}

{% block content %}
  <article>
      <div class="container">
          <div class="row">
              <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {{post.content|markdown}}
                <br>
                <p class="meta">
                  Tags {{  post.tags.all|join:", " }}
                </p>

              </div>
            </div>
        </div>

  </article>

{% endblock %}